Transform: AWS::Serverless-2016-10-31
Resources:
  OpenSearchServiceDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      ClusterConfig:
        InstanceCount: '1'
        InstanceType: 't3.small.search'
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: 'gp2'
  DefaultEncryptionPolicy:
    Type: 'AWS::OpenSearchServerless::SecurityPolicy'
    Properties:
      Name: default-encryption-policy
      Type: encryption
      Description: Encryption policy for test collection
      Policy: >-
        {"Rules":[{"ResourceType":"collection","Resource":["collection/passage-collection", "collection/song-collection"]}],"AWSOwnedKey":true}
  ProcessSongFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handlers
      Handler: process_song_function.handler
      Runtime: nodejs18.x
      MemorySize: 256
      Timeout: 60
      Environment:
        Variables:
          OPENSEARCH_URL: !Sub "https://${OpenSearchServiceDomain.DomainEndpoint}/"
      Policies:
        - Statement:
          - Effect: Allow
            Action: secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:us-east-2:448639809803:secret:*
        - Statement:
          - Effect: Allow
            Action:
              - 'es:ESHttp*'
            Resource: 
              Fn::Join:
                - ''
                - - 'arn:aws:es:'
                  - !Ref 'AWS::Region'
                  - ':'
                  - !Ref 'AWS::AccountId'
                  - ':domain/'
                  - !Ref OpenSearchServiceDomain
                  - '/*'
      Events:
        addSongToSearchQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt ProcessSongQueue.Arn
            BatchSize: 1
      Layers:
        - !Ref CommonLayer
  ProcessSongQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProcessSongDeadLetterQueue.Arn
        maxReceiveCount: 3
  ProcessSongDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
  RefreshUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handlers
      Handler: refresh_user_function.handler
      Runtime: nodejs18.x
      MemorySize: 256
      Timeout: 60
      Environment:
        Variables:
          OPENSEARCH_URL: !Sub "https://${OpenSearchServiceDomain.DomainEndpoint}/"
          REFRESHUSERQUEUE_QUEUE_URL: !Ref RefreshUserQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt RefreshUserQueue.QueueName
        - Statement:
          - Effect: Allow
            Action: secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:us-east-2:448639809803:secret:*
        - Statement:
          - Effect: Allow
            Action:
              - 'es:ESHttp*'
            Resource: 
              Fn::Join:
                - ''
                - - 'arn:aws:es:'
                  - !Ref 'AWS::Region'
                  - ':'
                  - !Ref 'AWS::AccountId'
                  - ':domain/'
                  - !Ref OpenSearchServiceDomain
                  - '/*'
      Events:
        addUserToRefreshQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt RefreshUserQueue.Arn
            BatchSize: 1
      Layers:
        - !Ref CommonLayer
  RefreshUserQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt RefreshUserDeadLetterQueue.Arn
        maxReceiveCount: 3
  RefreshUserDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
  ProcessUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handlers
      Handler: process_users_function.handler
      Runtime: nodejs18.x
      MemorySize: 256
      Timeout: 60
      Environment:
        Variables:
          PROCESSSONGQUEUE_QUEUE_URL: !Ref ProcessSongQueue
          REFRESHUSERQUEUE_QUEUE_URL: !Ref RefreshUserQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ProcessSongQueue.QueueName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt RefreshUserQueue.QueueName
        - Statement:
          - Effect: Allow
            Action: secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:us-east-2:448639809803:secret:*
      Events:
        ProcessUsersScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(3 minutes)
      Layers:
        - !Ref CommonLayer
  SwapSpotifyCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handlers
      Handler: swap_spotify_code_function.handler
      Runtime: nodejs18.x
      MemorySize: 256
      Timeout: 60
      Policies:
        - Statement:
          - Effect: Allow
            Action: secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:us-east-2:448639809803:secret:*
      Events:
        Api:
          Type: Api
          Properties:
            Path: /swap_spotify_code
            Method: POST
      Layers:
        - !Ref CommonLayer
  GetProphecy:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handlers
      Handler: get_prophecy.handler
      Runtime: nodejs18.x
      MemorySize: 256
      Timeout: 60
      Policies:
        - Statement:
          - Effect: Allow
            Action: secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:us-east-2:448639809803:secret:*
      Events:
        Api:
          Type: Api
          Properties:
            Path: /get_prophecy
            Method: POST
      Layers:
        - !Ref CommonLayer
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./shared/layer-package.zip
      CompatibleRuntimes:
        - nodejs18.x
  