import SentimentEnumType from '../types/sentiments';

export const allSentiments: SentimentEnumType[] = [
  // 'affectionate',
  // 'alienated',
  // 'angry',
  // 'appreciative',
  // 'betrayed',
  // 'bittersweet',
  // 'carefree',
  // 'celebratory',
  // 'chaotic',
  // 'conflicted',
  'desperate',
  // 'determined',
  // 'disillusioned',
  // 'dreamy',
  // 'empowered',
  // 'energetic',
  'enigmatic',
  'euphoric',
  // 'excited',
  // 'fearful',
  // 'flirtatious',
  // 'frustrated',
  'haunting',
  // 'heartbroken',
  'hopeful',
  'intimate',
  // 'introspective',
  // 'joyful',
  // 'liberating',
  'lonely',
  // 'loyal',
  // 'lustful',
  // 'melancholic',
  // 'nostalgic',
  // 'obsessive',
  // 'optimistic',
  // 'passionate',
  // 'peaceful',
  // 'philosophical',
  // 'playful',
  // 'provocative',
  // 'rebellious',
  // 'reckless',
  // 'regretful',
  // 'resilient',
  // 'romantic',
  // 'seductive',
  // 'sensual',
  // 'spiritual',
  // 'surreal',
  // 'triumphant',
  // 'violent',
  // 'vulnerable',
];

export const sentimentToEmojiMap: Record<SentimentEnumType, string> = {
  affectionate: '🥰',
  alienated: '👽',
  angry: '😡',
  appreciative: '🙏',
  betrayed: '🔪',
  bittersweet: '😔💛',
  carefree: '🤗',
  celebratory: '🎉',
  chaotic: '🤪',
  conflicted: '🤔',
  desperate: '😫',
  determined: '💪',
  disillusioned: '🤷‍♀️',
  dreamy: '🌈',
  empowered: '👊',
  energetic: '🤸‍♀️',
  enigmatic: '🧩',
  euphoric: '✨',
  excited: '🤩',
  fearful: '😱',
  flirtatious: '😉',
  frustrated: '😤',
  haunting: '👻',
  heartbroken: '💔',
  hopeful: '🤞',
  intimate: '💏',
  introspective: '🔍',
  joyful: '🥳',
  liberating: '🦋',
  lonely: '🌘',
  loyal: '🐶',
  lustful: '🥵',
  melancholic: '😢',
  nostalgic: '👵',
  obsessive: '🤤',
  optimistic: '🌞',
  passionate: '🔥',
  peaceful: '🕊️',
  philosophical: '📚',
  playful: '😄',
  provocative: '😏',
  rebellious: '🤘',
  reckless: '🏎️',
  regretful: '😔',
  resilient: '🌱',
  romantic: '💕',
  seductive: '😈',
  sensual: '🌹',
  spiritual: '🧘‍♀️',
  surreal: '🦄',
  triumphant: '🏆',
  violent: '🔫',
  vulnerable: '😳',
};
